//
//  SendDataRouter.swift
//  Data-Passing
//
//  Created by Krish on 25/06/19.
//  Copyright (c) 2019 Krish. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

import UIKit

@objc protocol SendDataRoutingLogic
{
    func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol SendDataDataPassing
{
    var dataStore: SendDataDataStore? { get }
}

class SendDataRouter: NSObject, SendDataRoutingLogic, SendDataDataPassing
{
    weak var viewController: SendDataViewController?
    var dataStore: SendDataDataStore?
    
    // MARK: Routing
    
    func routeToSomewhere(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! GetDataViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "GetDataViewController") as! GetDataViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
            navigateToSomewhere(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToSomewhere(source: SendDataViewController, destination: GetDataViewController)
    {
        source.show(destination, sender: nil)
    }
    
    //   MARK: Passing data
    
    func passDataToSomewhere(source: SendDataDataStore, destination: inout GetDataDataStore)
    {
        destination.name = source.name
    }
}
