//
//  SendDataPresenter.swift
//  Data-Passing
//
//  Created by Krish on 25/06/19.
//  Copyright (c) 2019 Krish. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SendDataPresentationLogic
{
    func presentSomething(response: SendData.Something.Response)
    func presentReciveData(response: SendData.Recive.Response)
}

class SendDataPresenter: SendDataPresentationLogic
{
    
    
    weak var viewController: SendDataDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: SendData.Something.Response)
    {
        
        let greeting = response.title.isEmpty ? "Hi" : "\(response.title)"
        let viewModel = SendData.Something.ViewModel(greeting: greeting)
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentReciveData(response: SendData.Recive.Response) {
        let viewModel = SendData.Recive.ViewModel()
        viewController?.displaygreeting(viewModel: viewModel)
    }
    
}
