//
//  GetDataModels.swift
//  Data-Passing
//
//  Created by Krish on 25/06/19.
//  Copyright (c) 2019 Krish. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
import UIKit

enum GetData
{
    // MARK: Use cases
    
    enum Something
    {
        struct Request
        {
            
        }
        struct Response
        {
            var name: String
        }
        struct ViewModel
        {
            var greeting:String
        }
    }
    enum Receive {
        struct Request:Codable
        {
            var title: String?
        }
        struct Response
        {
        }
        struct ViewModel
        {
        }
        
    }
}
