//
//  GetDataWorker.swift
//  Data-Passing
//
//  Created by Krish on 25/06/19.
//  Copyright (c) 2019 Krish. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
protocol SomeData {
    var title:String {get set}
}
class GetDataWorker:SomeData
{
    var title:String = ""
    var someData:GetData.Recive.Request?
    func doSomeWork()
    {
        var urlRequest = URLRequest(url: URL(string: "https://jsonplaceholder.typicode.com/todos/1")!)
        urlRequest.httpMethod = "GET"
        URLSession.shared.dataTask(with: urlRequest) { (data, resp, err) in
            print(data)
            do{
                self.someData = try JSONDecoder().decode(GetData.Recive.Request.self, from: data!)
                DispatchQueue.main.async {
                    print(self.someData?.title)
                }
            }catch{
                print("unable to respond")
            }
            }.resume()
    }
}
