//
//  GetDataInteractor.swift
//  Data-Passing
//
//  Created by Krish on 25/06/19.
//  Copyright (c) 2019 Krish. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GetDataBusinessLogic
{
    func doSomething(request: GetData.Something.Request)
    func sendData(reuest: GetData.Recive.Request)
}

protocol GetDataDataStore
{
    var name: String { get set }
}

class GetDataInteractor: GetDataBusinessLogic, GetDataDataStore
{
    
    
    var presenter: GetDataPresentationLogic?
    var worker: GetDataWorker?
    var name: String = ""
    
    // MARK: Do something
    func sendData(reuest: GetData.Recive.Request) {
        worker?.doSomeWork()
        if(worker?.someData?.title != nil)
        {
            name = (worker?.someData!.title)!
        }
        let response = GetData.Recive.Response()
        presenter?.presentSendData(response: response)
    }
    
    
    func doSomething(request: GetData.Something.Request)
    {
        worker = GetDataWorker()
        worker?.doSomeWork()
        
        let response = GetData.Something.Response(name: name)
        presenter?.presentSomething(response: response)
    }
}
