//
//  GetDataPresenter.swift
//  Data-Passing
//
//  Created by Krish on 25/06/19.
//  Copyright (c) 2019 Krish. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GetDataPresentationLogic
{
    func presentSomething(response: GetData.Something.Response)
    func presentSendData(response:GetData.Receive.Response)
}

class GetDataPresenter: GetDataPresentationLogic
{
    
    weak var viewController: GetDataDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: GetData.Something.Response) {
        let greeting = response.name.isEmpty ? "hello" : "\(response.name)"
        let viewModel = GetData.Something.ViewModel(greeting: greeting)
        viewController?.displaySomething(viewModel: viewModel)
    }
    func presentSendData(response: GetData.Receive.Response) {
        
        
        let viewModel = GetData.Receive.ViewModel()
        viewController?.displayGreeting(viewModel: viewModel)
        
    }
}
